"""initial tables

Revision ID: 6e0a71194713
Revises: 
Create Date: 2026-07-05 11:48:40.030900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0a71194713'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dental_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_from', sa.Integer(), nullable=False),
    sa.Column('price_to', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dental_service_pkey'))
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_pkey'))
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_pkey'))
    )
    op.create_index(op.f('patient_phone_idx'), 'patient', ['phone'], unique=True)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('dental_service_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'moved', name='appointmentstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dental_service_id'], ['dental_service.id'], name=op.f('appointment_dental_service_id_fkey')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('appointment_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('appointment_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_index(op.f('patient_phone_idx'), table_name='patient')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('dental_service')
    # ### end Alembic commands ###
