"""add_doctor_dental_service_relation

Revision ID: dfc6f7964a9b
Revises: 6e0a71194713
Create Date: 2026-07-07 11:00:03.640722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc6f7964a9b'
down_revision: Union[str, Sequence[str], None] = '6e0a71194713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_dental_servie',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('dental_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dental_service_id'], ['dental_service.id'], name=op.f('doctor_dental_servie_dental_service_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('doctor_dental_servie_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'dental_service_id', name=op.f('doctor_dental_servie_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_dental_servie')
    # ### end Alembic commands ###
